version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    network_mode: "host"  # This allows nginx to access localhost
    volumes:
      - ./default:/etc/nginx/conf.d/default.conf

  akordebi:
    image: akordebi:1.4
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nikoloz93
      MYSQL_DATABASE: akordebi.ge
      TZ: Asia/Tbilisi
    volumes:
      - mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  mysql-data:
