version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - DATABASE_HOST=mysql
    #   - DATABASE_USER=root
    #   - DATABASE_PASSWORD=nikoloz93
    #   - DATABASE_NAME=akordebi.ge
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: nikoloz93
      MYSQL_DATABASE: akordebi.ge
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: