version: '3'

services:
  web:
    image: akordebi:1.2  # Use the loaded image name here
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nikoloz93  # Use the actual root password you want to set
      MYSQL_DATABASE: akordebi.ge
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: