version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    # environment:
    #   - DATABASE_HOST=mysql
    #   - DATABASE_USER=root
    #   - DATABASE_PASSWORD=password
    #   - DATABASE_NAME=mydatabase
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: akordebi.ge
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: