export default {
    _metaTitle: "გიტარის აკორდები | gitaris akordebi",
    _metaDescription: "ქართული სიმღერების გიტარის აკორდები | Guitar chords of Georgian songs",
    _searchText: "მოძებნეთ სიმღერა ან ავტორი",
    _searchLabel: "აკორდების ძებნა",
    _filterPopularity: "პოპულარობით",
    _filterQuality: "ხარისხით",
    _filterDifficulty: "სირთულით",
    _videoIconTitle: "მიჩვენე მხოლოდ გაკვეთილით",
    _verifyIconTitle: "მიჩვენე მხოლოდ დამოწმებული",
    _uploadSong: "სიმღერის ატვირთვა",
    _isShown: "ნაჩვენებია",
    _from: "დან",
    _till: "მდე. სულ",
    _song: 'სიმღერა',
    _footer_designBy: "Designed and developed by",
    _footer_tsogi: "tsogi",
    _footer_input: 'აკორდების ძებნა',
    _footer_input_placeholder: 'მოგვწერეთ იდეები, შენიშვნები, მოსაზრებები',
    chord: {
        font: "ფონტი",
        autoScroll: "ავტო-სქროლი",
        chord: "აკორდების",
        hide: "დამალვა",
        appearance: "გამოჩენა",
        uploaded: "ატვირთა",
        rate: " შეაფასეთ აკორდების სისწორე",
    },
    upload: {
        publish: "სიმღერის akordebi.ge-ზე გამოსაქვეყნებლად შეავსეთ ველები და ატვირთეთ ტექსტი პლიუს(+) ღილაკების მეშვეობით. პროცესი არის მარტივი და ინტუიტიური. ასევე, ამ გვერდის ბოლოში, შეგიძლიათ ნახოთ",
        video_Instructions: "ტვირთვის ვიდეო ინსტრუქცია",
        video_ifream_title: "ატვირთვის ვიდეო ინსტრუქციები",
        song_name_input: "ჩაწერეთ სიმღერის სახელი",
        video_lesson_link: "ვიდეო გაკვეთილის ლინკი. მაგ. youtube.com/watch?v=O08BvtiPka8 (არასავალდებულო)",
        uploader_name: "ამტვირთის სახელი/გვარი (არასავალდებულო)",
        save: "სიმღერის შენახვა",
        editor_save: "შენახვა",
        editor_delete_title: "სტრიქონის წაშლა",
        editor_move_title: "სტრიქონის გადატანა",
        editor_duplicate_title: "სტრიქონის დუბლირება",
        editor_change_title: "სტრიქონის შეცვლა",
        editor_mark_title: "მისამღერად მონიშვნა",
        editor_mark_string_title: "სტრიქონად მონიშვნა",
        addition_right_hand_button: "მარჯვენა ხელის დამატება",
        add_string_button: "სტრიქონის დამატება",
        add_skip_button: "გამოტოვების დამატება",
        write_chord: "ჩაწერეთ აკორდი",
    },
}