version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    network_mode: "host"  # This allows nginx to access localhost
    volumes:
      - ./default:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro  # Add this line

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt

  akordebi:
    image: akordebi:1.4
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    depends_on:
      - mysql

  tsogi_manager:
    image: tsogi_manager:1.0  # Use the loaded image name here
    restart: unless-stopped
    ports: