import Head from 'next/head'
import Header from '@/components/Header'
import ChordsList from '@/components/ChordsList'
import Footer from '@/components/Footer'
import db from '@/services/db'

export default function Home({ initialSongs }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="App">
        <ChordsList initialSongs={initialSongs} />
      </div>
      <Footer />
    </>
  )
}

export async function getStaticProps() {
    let initialSongs = await db.getAllSongs();
  
    return {
      props: {
        initialSongs
      },
    }
}